name: Test lit-data library

on:
  push:
    branches: [master]
    paths: ["lit-data/**"]

  pull_request:
    branches: [master]
    paths: ["lit-data/**"]

jobs:
  test-lit-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lit-data

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.10"

      - name: Set up Poetry cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python get-poetry.py -y
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          rm get-poetry.py

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint with flake8
        run: poetry run flake8

      - name: Run tests with pytest
        run: poetry run pytest
